embystat:
  image: linuxserver/embystat
  container_name: embystat
  environment:
    - PUID=1000
    - PGID=1000
    - TZ=Europe/Minsk
  volumes:
    - /storage/config/embystat:/config
  ports:
    - 6555:6555
