doublecommander:
  image: linuxserver/doublecommander
  container_name: doublecommander
  # network_mode: host
  environment:
    - PUID=1000
    - PGID=1000
    - TZ=Europe/Minsk
    - UMASK_SET=022 #optional
    - DELUGE_LOGLEVEL=error #optional
  volumes:
    - /storage/config/doublecommander:/config
    - /storage/config:/configs
    - /storage/downloads:/downloads
    - /storage/media:/media
  ports:
    - 8112:8112
    - 58846:58846
    - 58946:58946
  restart: unless-stopped
