bazarr:
  image: linuxserver/bazarr
  container_name: bazarr
  environment:
    - PUID=1000
    - PGID=1000
    - TZ=Europe/Minsk
    - UMASK_SET=022 #optional
  volumes:
    - ./config/bazarr:/config
    - ./media/movies:/movies
    - ./media/tvshows:/tv
  ports:
    - 6767:6767
  restart: unless-stopped
