sonarr:
  image: linuxserver/sonarr
  container_name: sonarr
  environment:
    - PUID=1000
    - PGID=1000
    - TZ=Europe/Minsk
    - UMASK_SET=022 #optional
  volumes:
    - /storage/config/sonarr:/config
    - /storage/media/tvshows:/tv
    - /storage/downloads:/downloads
  ports:
    - 8989:8989
  restart: unless-stopped
