sabnzbd:
  image: ghcr.io/linuxserver/sabnzbd
  container_name: sabnzbd
  environment:
    - PUID=1000
    - PGID=1000
    - TZ=Europe/Minsk
  volumes:
    - /storage/config/sabnzbd:/config
    - /storage/downloads:/downloads
    - /storage/downloads/incomplete-downloads:/incomplete-downloads #optional
  ports:
    - 8080:8080
    - 9090:9090
