lidarr:
  image: linuxserver/lidarr
  container_name: lidarr
  environment:
    - PUID=1000
    - PGID=1000
    - TZ=Europe/Minsk
    - UMASK_SET=022 #optional
  volumes:
    - /storage/config/lidarr:/config
    - /storage/media/music:/music
    - /storage/downloads:/downloads
  ports:
    - 8686:8686
