lidarr:
  image: linuxserver/lidarr
  container_name: lidarr
  environment:
    - PUID=1000
    - PGID=1000
    - TZ=Europe/Minsk
    - UMASK_SET=022 #optional
  volumes:
    - ./config/lidarr:/config
    - ./media/music:/music
    - ./downloads:/downloads
  ports:
    - 8686:8686
