emby:
  image: linuxserver/emby
  container_name: emby
  environment:
    - PUID=1000
    - PGID=1000
    - TZ=Europe/Minsk
    - UMASK_SET=022 #optional
  volumes:
    - /storage/config/emby:/config
    - /storage/media/tvshows:/data/tvshows
    - /storage/media/movies:/data/movies
  ports:
    - 8096:8096
    - 8920:8920 #optional
