nginx:
  image: linuxserver/nginx
  container_name: nginx
  environment:
    - PUID=1000
    - PGID=1000
    - TZ=Europe/Minsk
  volumes:
    - ./config/nginx:/config
  ports:
    - 80:80
    - 443:443
