jackett:
  image: linuxserver/jackett
  container_name: jackett
  environment:
    - PUID=1000
    - PGID=1000
    - TZ=Europe/Minsk
    - AUTO_UPDATE=true #optional
    # - RUN_OPTS=<run options here> #optional
  volumes:
    - /storage/config/jackett:/config
    - /storage/downloads:/downloads
  ports:
    - 9117:9117
  restart: unless-stopped
