bitwardenrs:
  image: bitwardenrs/server:latest
  container_name: bitwardenrs
  environment:
    - PUID=1000
    - PGID=1000
    - TZ=Europe/Minsk
    - UMASK_SET=022 #optional
  volumes:
    - /storage/config/bitwardenrs:/data/
  ports:
    - 8100:80
  restart: unless-stopped
