plex:
  image: ghcr.io/linuxserver/plex:bionic
  container_name: plex
  network_mode: host
  environment:
    - PUID=1000
    - PGID=1000
    - VERSION=docker
    - UMASK_SET=022 #optional
    # - PLEX_CLAIM= #optional
  volumes:
    - ./config/plex:/config
    - ./media/tvshows:/tv
    - ./media/photo:/photo
    - ./media/audiobooks:/audiobooks
    - ./media/learn:/learn
    - ./media/music:/music
  restart: unless-stopped
