plex:
  image: ghcr.io/linuxserver/plex:bionic
  container_name: plex
  network_mode: host
  environment:
    - PUID=1000
    - PGID=1000
    - VERSION=docker
    - UMASK_SET=022 #optional
    # - PLEX_CLAIM= #optional
  volumes:
    - /storage/config/plex:/config
    - /storage/media/tvshows:/tv
    - /storage/media/photo:/photo
    - /storage/media/audiobooks:/audiobooks
    - /storage/media/learn:/learn
    - /storage/media/music:/music
  restart: unless-stopped
