nzbget:
  image: ghcr.io/linuxserver/nzbget
  container_name: nzbget
  environment:
    - PUID=1000
    - PGID=1000
    - TZ=Europe/Minsk
  volumes:
    - ./config/nzbget:/config
    - ./downloads:/downloads
  ports:
    - 6789:6789
  restart: unless-stopped
