radarr:
  image: linuxserver/radarr
  container_name: radarr
  environment:
    - PUID=0
    - PGID=0
    - TZ=Europe/Minsk
    - UMASK_SET=022 #optional
  volumes:
    - ./config/radarr:/config
    - ./media/movies:/movies
    - ./downloads:/downloads
  ports:
    - 7878:7878
  restart: unless-stopped
