radarr:
  image: linuxserver/radarr
  container_name: radarr
  environment:
    - PUID=0
    - PGID=0
    - TZ=Europe/Minsk
    - UMASK_SET=022 #optional
  volumes:
    - /storage/config/radarr:/config
    - /storage/media/movies:/movies
    - /storage/downloads:/downloads
  ports:
    - 7878:7878
  restart: unless-stopped
